// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDc6xvIO7XhUmOMBHNQ64Q5CfVwmO67Awc',
    appId: '1:596461488658:web:9b19c8a6cf797ee1ce26cb',
    messagingSenderId: '596461488658',
    projectId: 'astrophotography-blog',
    authDomain: 'astrophotography-blog.firebaseapp.com',
    storageBucket: 'astrophotography-blog.firebasestorage.app',
    measurementId: 'G-24HEHDCMT9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBskbczuSzA92vw3kS0aQIsSWrNbEdfqKI',
    appId: '1:596461488658:android:9077b3cfa41dd274ce26cb',
    messagingSenderId: '596461488658',
    projectId: 'astrophotography-blog',
    storageBucket: 'astrophotography-blog.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfzVvEFI8it26__0SCQ8mbwb6SgEeke9w',
    appId: '1:596461488658:ios:86f270e18e986eaace26cb',
    messagingSenderId: '596461488658',
    projectId: 'astrophotography-blog',
    storageBucket: 'astrophotography-blog.firebasestorage.app',
    iosBundleId: 'com.example.astrophotographyBlog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfzVvEFI8it26__0SCQ8mbwb6SgEeke9w',
    appId: '1:596461488658:ios:86f270e18e986eaace26cb',
    messagingSenderId: '596461488658',
    projectId: 'astrophotography-blog',
    storageBucket: 'astrophotography-blog.firebasestorage.app',
    iosBundleId: 'com.example.astrophotographyBlog',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDc6xvIO7XhUmOMBHNQ64Q5CfVwmO67Awc',
    appId: '1:596461488658:web:55319a9f1d2e8b98ce26cb',
    messagingSenderId: '596461488658',
    projectId: 'astrophotography-blog',
    authDomain: 'astrophotography-blog.firebaseapp.com',
    storageBucket: 'astrophotography-blog.firebasestorage.app',
    measurementId: 'G-WXFSYQ67BG',
  );
}
